### ISSUE TITLE
Support for nuxt.js

### ISSUE THREAD

**Issue by lukasborawski** [chryb/vue-popup#1]
It will be nice to have nuxt.js supported ;)

**Comment by biering** [comment]
I'm on it :)

**Comment by biering** [comment]
Hi, I've added an entry to the readme file. The problem was that VueUp is a client-side only lib and therefore you need to specify it as: `[ { src: '...', ssr: false } ]` under `nuxt.config.js`.

**Comment by lukasborawski** [comment]
@chryb there is `spa` mode now. So, this should work without the additional config setup. Thx though!

**Comment by biering** [comment]
@lukasborawski  I've added a note to the readme. Thank you for pointing it out.
