### ISSUE TITLE
index.js is missing

### ISSUE THREAD

**Issue by JukkaM** [chryb/vue-popup#10]
Package.json refers dist/index.js as main entrypoint of the package but there is no dist/index.js file. If it is supposed to show up after succesfull npm installation, it is not. I don't get any errors during npm install. This prevents me importing this package in my Vue application because webpack cannot find the package.

**Comment by endorfin** [comment]
Same for me after upgrade,. With previous 1.0.6 version it works.

This dependency was not found:
* vueup in ./src/main.js

**Comment by joelmandell** [comment]
@JukkaM @endorfin 
I will make a PR soon that I think fixes this.
