### ISSUE TITLE
IE11 Overlay is visible

### ISSUE THREAD

**Issue by joelmandell** [chryb/vue-popup#12]
When using vueup in IE11 the overlay is visible. 

![image](https://user-images.githubusercontent.com/109020/56804476-393f3380-6826-11e9-8e7d-efd5fc77def4.png)

**Comment by joelmandell** [comment]
Working on a fix for this...

**Comment by biering** [comment]
@joelmandell  Hi, I will fix VueUp and merge the PR this afternoon.

**Comment by joelmandell** [comment]
I really really appreciate it! Thank you!

> 
> 
> @joelmandell Hi, I will fix VueUp and merge the PR this afternoon.

**Comment by biering** [comment]
Merged. Sorry for the long response time.
